### ISSUE TITLE
_antdmove 文件是干嘛的为啥我这边引入后就报错了

### ISSUE THREAD

**Issue by Marszht** [ant-move/echarts-Aliapp#8]
想知道 _antdmove 是干嘛的 ? 
为啥我这边引入后就报错了

**Comment by ZhQiushi** [comment]
您好，报什么错？可以尝试使用alipay-compile命令，https://github.com/ant-move/Antmove/blob/master/packages/%40antmove/alipay-polyfill-plugin/README.md

**Comment by Marszht** [comment]
> 您好，报什么错？可以尝试使用alipay-compile命令，https://github.com/ant-move/Antmove/blob/master/packages/%40antmove/alipay-polyfill-plugin/README.md

好的 ,谢谢了

**Comment by Marszht** [comment]
thanks
